# Module: mssql
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.15/metricbeat-module-mssql.html

- module: mssql
  metricsets:
    - "transaction_log"
    - "performance"
  hosts: ["sqlserver://0.0.0.0"]
  username: sa
  password: pass
  period: 10s

